logging:
  log_format: '[%(asctime)s] %(levelname)s:%(name)s %(message)s'
  log_file: "campaign.log"

aws:
  s3:
    bucket: "test-blog-nest"
    region: "ap-south-1"
    path-region: "s3.ap-south-1"

encryption:
  service:
    encrypt_url_localhost: "127.0.0.1:5000/campaigns"
    path: "routes/tmp"
    api_version: "v1"

auth:
  app_name: Auth
  api_domain: http://localhost:8000 
  website_domain: http://localhost:3000
  api_base_path: /auth
  website_base_path: /auth
  supertokens_core_uri: http://172.18.0.2:3567
  user_management_dashboard_api_key : supertoken

uploadcare:
  uploadcare_url_parameter : ucarecdn.com
  uploadcare_file_size:
    file_size : 5 # In MB

version:
  api_version : "v1"

# uploadcare-file-size:
#   file-size : 5 # In MB

cors: 
  allowed_origins:
    - http://localhost:3000
    - http://localhost:5173
    - http://localhost:3001
  allowed_methods:
    - GET 
    - POST 
    - PUT 
    - HEAD
    - OPTIONS
    - DELETE
  allowed_headers:
    - Content-Type
    - Access-Control-Allow-Headers
    - Authorization
    - Access-Control-Allow-Origin
    
size:
  pagesize : 8